typography_spectrum: 0.7901766586583108
color:
  saturation: 0.9776150844991207
  brandStrength: 0.020341907162219286
  lightness: 0.9469832426402718
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.39028026117011905
opengraph:
  appId: 'https://www.facebook.com/spartan.colombia/?ref=aymt_homepage_panel'
layout_spectrum: 0.5089138927869499
author:
  email: sales@spartnaworld.co
  name: Spartan World
name: Spartan World
navigation:
  - name: Facebook Page
    url: 'https://www.facebook.com/spartan.colombia/?ref=aymt_homepage_panel'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7c7b8d81-2f0a-461b-a948-44d89a55f3af.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ''
