typography_spectrum: 0.5451563715469092
color:
  saturation: 0.1044064920861274
  brandStrength: 0.8662658056709915
  lightness: 0.6797506401780993
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.5304595364723355
opengraph:
  appId: 'https://www.facebook.com/spartan.colombia/?ref=aymt_homepage_panel'
layout_spectrum: 0.33685517706908286
author:
  email: sales@spartnaworld.co
  name: Spartan World
name: Spartan World
navigation:
  - name: Facebook Page
    url: 'https://www.facebook.com/spartan.colombia/?ref=aymt_homepage_panel'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7c7b8d81-2f0a-461b-a948-44d89a55f3af.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Spartan
description: Footer
