typography_spectrum: 0.8148153878282756
color:
  brandStrength: 0.03399427514523268
  lightness: 0.907429409911856
  saturation: 0.8807718835305423
  rhythmicContrast: 0.49348144442774355
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.4233945293817669
author:
  email: sales@spartnaworld.co
  name: Spartan World
name: Spartan World
navigation:
  - name: Spartan Paintball
    url: 'https://www.facebook.com/spartan.colombia/?ref=aymt_homepage_panel'
    type: external
  - name: A Fresh Take On Coffee T-Shirts
    id: 3877f2cf-260e-4749-85c5-2220fe021978
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7c7b8d81-2f0a-461b-a948-44d89a55f3af.png
title: Spartan World
